name: Build SunamoRuleset

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    name: Build SunamoRuleset
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore SunamoRuleset/SunamoRuleset.csproj

    - name: Build
      run: dotnet build SunamoRuleset/SunamoRuleset.csproj --configuration Release --no-restore

  test:
    name: Test SunamoRuleset.Tests
    runs-on: ${{ matrix.os }}
    needs: build

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore SunamoRuleset.Tests/SunamoRuleset.Tests.csproj

    - name: Build tests
      run: dotnet build SunamoRuleset.Tests/SunamoRuleset.Tests.csproj --configuration Release --no-restore

    - name: Run tests
      run: dotnet test SunamoRuleset.Tests/SunamoRuleset.Tests.csproj --configuration Release --no-build --verbosity normal
      continue-on-error: true
